//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActFlow
    {
        public ActFlow()
        {
            this.Steps = new HashSet<Step>();
        }
    
        public int id { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idStep { get; set; }
        public Nullable<int> idAction { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Step Step { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
    }
}
