//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionDescription
    {
        public int id { get; set; }
        public int ActionTemplate { get; set; }
        public Nullable<int> MapZone { get; set; }
        public string ActionText { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> Class { get; set; }
    
        public virtual MapZone MapZone1 { get; set; }
        public virtual ActionTemplate ActionTemplate1 { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Race Race1 { get; set; }
    }
}
