//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionResult
    {
        public ActionResult()
        {
            this.ActionResultDesires = new HashSet<ActionResultDesire>();
        }
    
        public int Id { get; set; }
        public string Predisposition { get; set; }
        public int Gold { get; set; }
        public int Expirience { get; set; }
        public int Artifact { get; set; }
        public bool SoulShard { get; set; }
        public bool Killed { get; set; }
        public int Action { get; set; }
    
        public virtual Action Action1 { get; set; }
        public virtual ICollection<ActionResultDesire> ActionResultDesires { get; set; }
    }
}
