//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTemplatePredisposition
    {
        public int id { get; set; }
        public int ActionTemplate { get; set; }
        public int Predisposition { get; set; }
        public int RequirementLow { get; set; }
        public int RequirementHight { get; set; }
    
        public virtual ActionTemplate ActionTemplate1 { get; set; }
        public virtual Predisposition Predisposition1 { get; set; }
    }
}
