//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTemplate
    {
        public ActionTemplate()
        {
            this.ActionTemplateActionDescriptions = new HashSet<ActionTemplateActionDescription>();
            this.ActionTemplatePredispositions = new HashSet<ActionTemplatePredisposition>();
            this.StepTemplateActionTemplates = new HashSet<StepTemplateActionTemplate>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public double PredispositionResult { get; set; }
    
        public virtual ICollection<ActionTemplateActionDescription> ActionTemplateActionDescriptions { get; set; }
        public virtual ICollection<ActionTemplatePredisposition> ActionTemplatePredispositions { get; set; }
        public virtual ICollection<StepTemplateActionTemplate> StepTemplateActionTemplates { get; set; }
    }
}
