//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class artEntities : DbContext
    {
        public artEntities()
            : base("name=artEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActFlow> ActFlows { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Artifact> Artifacts { get; set; }
        public virtual DbSet<ArtifactType> ArtifactTypes { get; set; }
        public virtual DbSet<ArtifactTypeBonu> ArtifactTypeBonus { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<Constellation> Constellations { get; set; }
        public virtual DbSet<ConstellationBonu> ConstellationBonus { get; set; }
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Talent> Talents { get; set; }
        public virtual DbSet<UserArtifact> UserArtifacts { get; set; }
        public virtual DbSet<UserTalent> UserTalents { get; set; }
    }
}
