//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public Carrier()
        {
            this.CarrierPredispositions = new HashSet<CarrierPredisposition>();
            this.CharrierCharacteristics = new HashSet<CharrierCharacteristic>();
        }
    
        public int id { get; set; }
        public int Race { get; set; }
        public int ExpirienceLevel { get; set; }
        public int ExpiriencePoints { get; set; }
    
        public virtual Race Race1 { get; set; }
        public virtual ICollection<CarrierPredisposition> CarrierPredispositions { get; set; }
        public virtual ICollection<CharrierCharacteristic> CharrierCharacteristics { get; set; }
    }
}
