//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierDesire
    {
        public int Id { get; set; }
        public int CarrierId { get; set; }
        public int DesireId { get; set; }
        public string DesireMask { get; set; }
        public int AddictionRequirement { get; set; }
        public bool IsSecret { get; set; }
        public int DefaultValue { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Desire Desire { get; set; }
    }
}
