//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System.Collections.Generic;

    public partial class Class
    {
        public Class()
        {
            this.ActionDescriptions = new HashSet<ActionDescription>();
            this.UserArtifactClasses = new HashSet<UserArtifactClass>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public int FibonacciSeed { get; set; }
    
        public virtual ICollection<ActionDescription> ActionDescriptions { get; set; }
        public virtual ICollection<UserArtifactClass> UserArtifactClasses { get; set; }
    }
}
