//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstellationBonu
    {
        public int Id { get; set; }
        public int Bonus { get; set; }
        public int Constallation { get; set; }
        public double Modifier { get; set; }
    
        public virtual Bonu Bonu { get; set; }
        public virtual Constellation Constellation { get; set; }
    }
}
