//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesireActionTemplateResult
    {
        public int id { get; set; }
        public int Desire { get; set; }
        public int ActionTemplateResult { get; set; }
        public double Modifier { get; set; }
    
        public virtual ActionTemplateResult ActionTemplateResult1 { get; set; }
        public virtual Desire Desire1 { get; set; }
    }
}
