//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ArtifactAdmin.DAL.Models
{
    public partial class Log
    {
        public int Id { get; set; }
        public string ShortLog { get; set; }
        public string ExtendedLog { get; set; }
        public DateTime Date { get; set; }
        public int UserArtifact { get; set; }
    
        public virtual UserArtifact UserArtifact1 { get; set; }
    }
}
