//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System.Collections.Generic;

    public partial class MapInfoDimension
    {
        public MapInfoDimension()
        {
            this.MiddlePoints = new HashSet<MiddlePoint>();
            this.DimentionRadius = new HashSet<DimentionRadiu>();
            this.PathFinderConfigs = new HashSet<PathFinderConfig>();
        }
    
        public int Id { get; set; }
        public int Dimension { get; set; }
        public int MapInfo { get; set; }
    
        public virtual MapInfo MapInfo1 { get; set; }
        public virtual ICollection<MiddlePoint> MiddlePoints { get; set; }
        public virtual ICollection<DimentionRadiu> DimentionRadius { get; set; }
        public virtual ICollection<PathFinderConfig> PathFinderConfigs { get; set; }
    }
}
