//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ArtifactAdmin.DAL.Models
{
    public partial class MapInfoDimension
    {
        public MapInfoDimension()
        {
            this.MiddlePoints = new HashSet<MiddlePoint>();
            this.DimentionRadius = new HashSet<DimentionRadiu>();
        }
    
        public int Id { get; set; }
        public int Dimension { get; set; }
        public int MapInfo { get; set; }
    
        public virtual MapInfo MapInfo1 { get; set; }
        public virtual ICollection<MiddlePoint> MiddlePoints { get; set; }
        public virtual ICollection<DimentionRadiu> DimentionRadius { get; set; }
    }
}
