//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System.Collections.Generic;

    public partial class MapInfo
    {
        public MapInfo()
        {
            this.ZoneCoordinats = new HashSet<ZoneCoordinat>();
            this.MapInfoDimensions = new HashSet<MapInfoDimension>();
            this.PathFinderConfigs = new HashSet<PathFinderConfig>();
        }
    
        public int Id { get; set; }
        public string MapName { get; set; }
        public string ImagePath { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual ICollection<ZoneCoordinat> ZoneCoordinats { get; set; }
        public virtual ICollection<MapInfoDimension> MapInfoDimensions { get; set; }
        public virtual ICollection<PathFinderConfig> PathFinderConfigs { get; set; }
    }
}
