//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System.Collections.Generic;

    public partial class MapObject
    {
        public MapObject()
        {
            this.MapObjectProbabilities = new HashSet<MapObjectProbability>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MapObjectProbability> MapObjectProbabilities { get; set; }
    }
}
