//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiddlePoint
    {
        public MiddlePoint()
        {
            this.MiddlePointNeighbors = new HashSet<MiddlePointNeighbor>();
        }
    
        public int Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string RelatedCoordinates { get; set; }
        public int MapInfoDimension { get; set; }
    
        public virtual MapInfoDimension MapInfoDimension1 { get; set; }
        public virtual ICollection<MiddlePointNeighbor> MiddlePointNeighbors { get; set; }
    }
}
