//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathFinderConfig
    {
        public int Id { get; set; }
        public int MapInfo { get; set; }
        public int MapInfoDimention { get; set; }
        public int DimentionRadius { get; set; }
        public int OrderIndex { get; set; }
    
        public virtual DimentionRadiu DimentionRadiu { get; set; }
        public virtual MapInfo MapInfo1 { get; set; }
        public virtual MapInfoDimension MapInfoDimension { get; set; }
    }
}
