//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ArtifactAdmin.DAL.Models
{
    public partial class Predisposition
    {
        public Predisposition()
        {
            this.ActionPredispositions = new HashSet<ActionPredisposition>();
            this.ActionTemplatePredispositions = new HashSet<ActionTemplatePredisposition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Mask { get; set; }
        public int Length { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<ActionPredisposition> ActionPredispositions { get; set; }
        public virtual ICollection<ActionTemplatePredisposition> ActionTemplatePredispositions { get; set; }
    }
}
