//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.ActionProperties = new HashSet<ActionProperty>();
            this.ActionTemplateProperties = new HashSet<ActionTemplateProperty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Mask { get; set; }
        public int Deviation { get; set; }
    
        public virtual ICollection<ActionProperty> ActionProperties { get; set; }
        public virtual ICollection<ActionTemplateProperty> ActionTemplateProperties { get; set; }
    }
}
