//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public Quest()
        {
            this.ActionResults = new HashSet<ActionResult>();
            this.QuestSteps = new HashSet<QuestStep>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Carrier { get; set; }
    
        public virtual ICollection<ActionResult> ActionResults { get; set; }
        public virtual Carrier Carrier1 { get; set; }
        public virtual ICollection<QuestStep> QuestSteps { get; set; }
    }
}
