//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceDesire
    {
        public int Id { get; set; }
        public int RaceId { get; set; }
        public int DesireId { get; set; }
        public double Probability { get; set; }
        public int DefaultValue { get; set; }
        public Nullable<int> Deviation { get; set; }
    
        public virtual Desire Desire { get; set; }
        public virtual Race Race { get; set; }
    }
}
