//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.Carriers = new HashSet<Carrier>();
        }
    
        public string Description { get; set; }
        public int id { get; set; }
        public int Strength { get; set; }
        public int Armor { get; set; }
        public int Agility { get; set; }
        public int Accuracy { get; set; }
        public int Knowledge { get; set; }
        public int Intellect { get; set; }
        public int HitPoints { get; set; }
        public int MoveSpeed { get; set; }
        public int Size { get; set; }
        public int Charisma { get; set; }
        public int ResistanceToArtifact { get; set; }
        public double Kindness { get; set; }
        public double Temperance { get; set; }
        public double Bravery { get; set; }
        public double Eloquence { get; set; }
        public double Cunning { get; set; }
        public double Inventiveness { get; set; }
        public double Observation { get; set; }
        public double Stealthy { get; set; }
        public double StrengthLevelModifier { get; set; }
        public double ArmorLevelModifier { get; set; }
        public double AgilityLevelModifier { get; set; }
        public double AccuracyLevelModifier { get; set; }
        public double KnowledgeLevelModifier { get; set; }
        public double IntellectLevelModifier { get; set; }
    
        public virtual ICollection<Carrier> Carriers { get; set; }
    }
}
