//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int idUser { get; set; }
        public int kStep { get; set; }
        public int kAct { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> nStep { get; set; }
        public Nullable<int> nAct { get; set; }
        public int id { get; set; }
    }
}
