//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.Actions = new HashSet<Action>();
            this.ActiveActionInFlows = new HashSet<ActiveActionInFlow>();
        }
    
        public int Id { get; set; }
        public int UserArtifact { get; set; }
        public Nullable<int> ActiveActionInFlow { get; set; }
        public string Text { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public Nullable<int> XCoordinate { get; set; }
        public Nullable<int> YCoordinate { get; set; }
        public Nullable<int> Desire { get; set; }
        public Nullable<bool> IsKey { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<ActiveActionInFlow> ActiveActionInFlows { get; set; }
        public virtual ActiveActionInFlow ActiveActionInFlow1 { get; set; }
        public virtual Desire Desire1 { get; set; }
    }
}
