//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepObjectType
    {
        public StepObjectType()
        {
            this.StepObjects = new HashSet<StepObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StepObject> StepObjects { get; set; }
    }
}
