//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepTemplate
    {
        public StepTemplate()
        {
            this.StepObjectStepTemplates = new HashSet<StepObjectStepTemplate>();
            this.StepTemplateActionTemplates = new HashSet<StepTemplateActionTemplate>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public string StepText { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StepObjectStepTemplate> StepObjectStepTemplates { get; set; }
        public virtual ICollection<StepTemplateActionTemplate> StepTemplateActionTemplates { get; set; }
    }
}
