//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.ActFlows = new HashSet<ActFlow>();
            this.Actions = new HashSet<Action>();
        }
    
        public int id { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idActFlow { get; set; }
    
        public virtual ICollection<ActFlow> ActFlows { get; set; }
        public virtual ActFlow ActFlow { get; set; }
        public virtual ICollection<Action> Actions { get; set; }
    }
}
