//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent
    {
        public Talent()
        {
            this.UserTalents = new HashSet<UserTalent>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int MaxLevel { get; set; }
        public double Modifier { get; set; }
    
        public virtual ICollection<UserTalent> UserTalents { get; set; }
    }
}
