//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserArtifact
    {
        public UserArtifact()
        {
            this.UserArtifactTalents = new HashSet<UserArtifactTalent>();
        }
    
        public int id { get; set; }
        public int Artifact { get; set; }
        public string Description { get; set; }
        public int Constellation { get; set; }
        public int TotalEnergy { get; set; }
        public double EnergyRegenRate { get; set; }
        public int PredictionRadius { get; set; }
        public long ExperiencePoints { get; set; }
        public int ExperienceLevel { get; set; }
        public int User { get; set; }
    
        public virtual Artifact Artifact1 { get; set; }
        public virtual Constellation Constellation1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserArtifactTalent> UserArtifactTalents { get; set; }
    }
}
