//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ArtifactAdmin.DAL.Models
{
    public partial class UserArtifact
    {
        public UserArtifact()
        {
            this.CarrierUserArtifacts = new HashSet<CarrierUserArtifact>();
            this.Logs = new HashSet<Log>();
            this.UserArtifactClasses = new HashSet<UserArtifactClass>();
            this.UserArtifactTalents = new HashSet<UserArtifactTalent>();
        }
    
        public int Id { get; set; }
        public int Artifact { get; set; }
        public string Description { get; set; }
        public int Constellation { get; set; }
        public int TotalEnergy { get; set; }
        public double EnergyRegenRate { get; set; }
        public int PredictionRadius { get; set; }
        public long ExperiencePoints { get; set; }
        public int ExperienceLevel { get; set; }
        public int User { get; set; }
        public int Carrier { get; set; }
        public int Energy { get; set; }
    
        public virtual Artifact Artifact1 { get; set; }
        public virtual ICollection<CarrierUserArtifact> CarrierUserArtifacts { get; set; }
        public virtual Constellation Constellation1 { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<UserArtifactClass> UserArtifactClasses { get; set; }
        public virtual ICollection<UserArtifactTalent> UserArtifactTalents { get; set; }
        public virtual User User1 { get; set; }
    }
}
