//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserArtifactClass
    {
        public int id { get; set; }
        public int Class { get; set; }
        public int UserArtifact { get; set; }
        public int Expirience { get; set; }
        public int ClassLevel { get; set; }
    
        public virtual Class Class1 { get; set; }
        public virtual UserArtifact UserArtifact1 { get; set; }
    }
}
