//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtifactAdmin.DAL.Models
{
    public partial class ZoneCoordinat
    {
        public int Id { get; set; }
        public int MapZone { get; set; }
        public int MapInfo { get; set; }
        public string Coordinates { get; set; }
    
        public virtual MapZone MapZone1 { get; set; }
        public virtual MapInfo MapInfo1 { get; set; }
    }
}
