//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class artEntities : DbContext
    {
        public artEntities()
            : base("name=artEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActFlow> ActFlows { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
    
        [DbFunction("artEntities", "GetChain")]
        public virtual IQueryable<GetChain_Result> GetChain(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChain_Result>("[artEntities].[GetChain](@id)", idParameter);
        }
    }
}
