//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationConstellation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtifactAdmin.DAL.Resources.Models.Constelltions.ValidationStrings", typeof(ValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть дію!.
        /// </summary>
        public static string RequiredActionTemplate {
            get {
                return ResourceManager.GetString("RequiredActionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть колір!.
        /// </summary>
        public static string RequiredColor {
            get {
                return ResourceManager.GetString("RequiredColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть опис!.
        /// </summary>
        public static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть іконку!.
        /// </summary>
        public static string RequiredIcon {
            get {
                return ResourceManager.GetString("RequiredIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть довжину рядка!.
        /// </summary>
        public static string RequiredLength {
            get {
                return ResourceManager.GetString("RequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть хоч би один рядок в список!.
        /// </summary>
        public static string RequiredList {
            get {
                return ResourceManager.GetString("RequiredList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть маску!.
        /// </summary>
        public static string RequiredMask {
            get {
                return ResourceManager.GetString("RequiredMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву!.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть початкову позицію!.
        /// </summary>
        public static string RequiredPosition {
            get {
                return ResourceManager.GetString("RequiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть текст!.
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву зони !.
        /// </summary>
        public static string RequiredZoneName {
            get {
                return ResourceManager.GetString("RequiredZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевищена довжина рядка!.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
    }
}
